server:
  port: 80
spring:
  application:
    name: consumer-order

  #sleuth和zipkin相关
  zipkin:
    base-url: http://localhost:9411/    #默认就是这个
  sleuth:
    sampler:
      probability: 1    #采样率值介于0-1之间，1表示全部采集

eureka:
  client:
    register-with-eureka: false   #不向Eureka注册中心注册
    service-url:
#      单机配置
#      defaultZone: http://eureka8411:8411/eureka
      #集群配置
      defaultZone: http://eureka8411:8411/eureka,http://eureka8412:8412/eureka,http://eureka8413:8413/eureka