server:
  port: 8411
spring:
  application:
    name: eureka-server-8411

eureka:
  instance:
    hostname: eureka8411
  client:
    register-with-eureka: false   #表示是否向Eureka注册中心注册自己
    fetch-registry: false   #表示自己为注册中心
    service-url:
#      单机配置
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群配置
      defaultZone: http://eureka8412:8412/eureka,http://eureka8413:8413/eureka
#  server:
#    #关闭自我保护机制
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 2000