server:
  port: 8491
spring:
  application:
    name: seata-business-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
seata:
  enabled: true   #默认为true
  tx-service-group: default_tx_group
  service:
    vgroup-mapping:
      default_tx_group: default
    grouplist:
      default: 127.0.0.1:8091
    disable-global-transaction: false
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      group : "SEATA_GROUP"
      namespace: ""
      dataId: "seataServer.properties"
      username: "nacos"
      password: "nacos"
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group : "SEATA_GROUP"
      namespace: ""
      username: "nacos"
      password: "nacos"
feign:
  client:
    config:
      default:
        connectTimeout: 3000    #TODO 验证连接时间
        readTimeout: 3000
  sentinel:
    enabled: true
