server:
  port: 80
spring:
  application:
    name: consumer-order-consul
  cloud:
    consul:
      discovery:
        hostname: 127.0.0.1
        port: 8500
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
#        prefer-ip-address: true