server:
  port: 8448
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
#      discovery:    #是否与服务发现组件进行结合，通过 serviceId(必须设置成大写) 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
#        locator:    #路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId/**，其中微服务应用名默认大写访问。
#          enabled: true
      routes:
        - id: payment_route             #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8401    #匹配后提供服务的路由地址
          uri: lb://provider-payment    #通过微服务名匹配
          predicates:
            - Path=/payment/**          #断言，路径相匹配的进行路由转发
#            - After=2022-03-11T10:33:32.348+08:00[Asia/Shanghai]   #ZonedDateTime.now()时间之后触发,Before、Between类似
#            - Cookie=username,gzh       #携带cookie为username=gzh的匹配    测试：curl http://localhost:8448/payment/2 --cookie "username=gzh"
#            - Header=X-Request-Id, \d+  #请求头要有X-Request-Id属性并值为整数的正则表达式   测试：curl http://localhost:8448/payment/2 -H "X-Request-Id:11"
#            - Host=**.hostname.org,**.anotherhost.org   #匹配host    测试：curl http://localhost:8448/payment/2 -H "Host:www.hostname.org"
#            - Method=GET    #匹配get请求
#            - Query=username, \d+   #要有参数名username并且值是整数    测试：curl http://localhost:8448/payment/2?username=11
#          filters:    #官网地址：https://docs.spring.io/spring-cloud-gateway/docs/2.2.9.RELEASE/reference/html/#gatewayfilter-factories
#            - AddRequestParameter=X-Request-Id, 123
eureka:
  client:
    service-url:
      #集群配置
      defaultZone: http://eureka8411:8411/eureka,http://eureka8412:8412/eureka,http://eureka8413:8413/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
