server:
  port: 8453
spring:
  application:
    name: cloud-stream-rabbitmq-consumer
  cloud:
    stream:
      binders:    # 此处配置要绑定的RabbitMQ的服务信息
        defaultRabbit:    # 定义的名称，用于与binding整合
          type: rabbit    # 消息组件类型
          environment:    # 设置RabbitMQ的相关环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings:   # 服务的整合处理
        input:   # 这个名字是一个通道的名称
          destination: studyExchange    # 要使用的Exchange名称定义
          content-type: application/json    # 设置消息类型
          binder: defaultRabbit     # 要绑定的消息服务的具体设置
          group: gzh1     # 分组，组内成员只处理一个消息 ；还有持久化功能，即重启服务后继续处理未完成的消息

eureka:
  client:
    service-url:
      #集群配置
      defaultZone: http://eureka8411:8411/eureka,http://eureka8412:8412/eureka,http://eureka8413:8413/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}